language: node_js
node_js: node

cache:
  directories:
    - "node_modules"

script:
  - yarn lint
  - yarn test

deploy:
  provider: npm
  email: chris@jaynes.me
  api_key: $NPM_TOKEN
  on:
    tags: true
